# Generated by Django 3.2.6 on 2021-08-10 15:14

from django.db import migrations, models
import froala_editor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('author', models.CharField(max_length=200)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('cpa', 'CPA'), ('eco', 'ECOMMERCE'), ('drop', 'DROPSHIPPING'), ('risk', 'RISKING'), ('script', 'SCRIPTS'), ('auto', 'AUTO')], max_length=16)),
                ('content', froala_editor.fields.FroalaField(blank=True, null=True)),
                ('intro', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='PostVIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('author', models.CharField(max_length=200)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('cpa', 'CPA'), ('eco', 'ECOMMERCE'), ('drop', 'DROPSHIPPING'), ('risk', 'RISKING'), ('script', 'SCRIPTS'), ('auto', 'AUTO')], max_length=16)),
                ('content', froala_editor.fields.FroalaField(blank=True, null=True)),
                ('intro', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
