# Generated by Django 3.2.6 on 2021-08-10 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumb',
            field=models.ImageField(default='profile.jpg', upload_to='media/%y/%m/%d'),
        ),
        migrations.AddField(
            model_name='postvip',
            name='thumb',
            field=models.ImageField(default='profile.jpg', upload_to='media/%y/%m/%d'),
        ),
    ]
