# Generated by Django 3.2.6 on 2021-08-10 17:04

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210810_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='postvip',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
    ]
