# Generated by Django 3.2.6 on 2021-08-10 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_postvip_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('CPA', 'CPA'), ('ECOMMERCE', 'ECOMMERCE'), ('DROPSHIPPING', 'DROPSHIPPING'), ('RISKING', 'RISKING'), ('SCRIPTS', 'SCRIPTS'), ('AUTO', 'AUTO')], max_length=16),
        ),
        migrations.AlterField(
            model_name='postvip',
            name='status',
            field=models.CharField(choices=[('CPA', 'CPA'), ('ECOMMERCE', 'ECOMMERCE'), ('DROPSHIPPING', 'DROPSHIPPING'), ('RISKING', 'RISKING'), ('SCRIPTS', 'SCRIPTS'), ('AUTO', 'AUTO')], max_length=16),
        ),
    ]
