# Generated by Django 3.2.6 on 2021-08-13 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210810_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumb',
            field=models.ImageField(default='profile.jpg', upload_to='photos/%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='postvip',
            name='thumb',
            field=models.ImageField(default='profile.jpg', upload_to='photos/%y/%m/%d'),
        ),
    ]
