# Generated by Django 3.2.6 on 2021-08-16 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210813_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='intro',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='post',
            name='thumb',
            field=models.ImageField(default='profile.jpg', upload_to='photos/%y/%d'),
        ),
        migrations.AlterField(
            model_name='postvip',
            name='intro',
            field=models.TextField(max_length=500),
        ),
    ]
