# Generated by Django 3.2.6 on 2021-08-15 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('thumb', models.ImageField(default='profile.jpg', upload_to='prod/')),
                ('acc', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
