# Generated by Django 3.2.6 on 2021-08-15 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='shopp',
        ),
    ]
