# Generated by Django 3.2.6 on 2021-08-17 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_shoporder_acc'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopp',
            name='acclst',
            field=models.CharField(default='acclist', max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='shopp',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
