# Generated by Django 3.2.6 on 2021-08-18 20:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0006_auto_20210817_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoporder',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='shoporder',
            name='user',
            field=models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, related_name='timesheet', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shopp',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='shoporder',
            unique_together={('user', 'title')},
        ),
    ]
