# Generated by Django 3.2.6 on 2021-08-18 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20210818_2014'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shoporder',
            unique_together=set(),
        ),
    ]
