# Generated by Django 3.2.6 on 2021-08-19 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zearch', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zearch',
            name='description',
        ),
        migrations.RemoveField(
            model_name='zearch',
            name='update',
        ),
    ]
