# Generated by Django 3.2.6 on 2021-08-28 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_username_userpass_usernam'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpass',
            name='ip',
            field=models.CharField(default='None', max_length=150),
        ),
        migrations.AlterField(
            model_name='userpass',
            name='password',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='userpass',
            name='usernam',
            field=models.CharField(max_length=150),
        ),
    ]
